
rest_api:
    resource: "@MyAppBundle/Resources/config/secure_routing.yml"
    prefix: /secure

catalog:
    type:     annotation
    resource: SyedOmair\Bundle\MyAppBundle\Controller\CatalogController

category:
    type:     annotation
    resource: SyedOmair\Bundle\MyAppBundle\Controller\CategoryController

product:
    type:     annotation
    resource: SyedOmair\Bundle\MyAppBundle\Controller\ProductController
